-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS music.composer
(
    composer_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    surname text COLLATE pg_catalog."default" NOT NULL,
    second_name text COLLATE pg_catalog."default",
    country_id integer,
    date_birth date,
    date_death date,
    CONSTRAINT composer_pkey PRIMARY KEY (composer_id),
    CONSTRAINT composer_unique_name_birth UNIQUE (name, surname, second_name, date_birth)
);

CREATE TABLE IF NOT EXISTS music.composer_countries
(
    composer_id integer,
    composer_name text COLLATE pg_catalog."default",
    country_name text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS music.countries
(
    country_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT countries_pkey PRIMARY KEY (country_id),
    CONSTRAINT country_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS music.genres
(
    genre_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT genres_pkey PRIMARY KEY (genre_id),
    CONSTRAINT genre_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS music.music
(
    music_id integer NOT NULL,
    composer_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    duration text COLLATE pg_catalog."default",
    finished_date date,
    premier_date date,
    premier_place text COLLATE pg_catalog."default",
    country_id integer,
    CONSTRAINT music_pkey PRIMARY KEY (music_id),
    CONSTRAINT music_unique_composer_name UNIQUE (composer_id, name)
);

CREATE TABLE IF NOT EXISTS music.music_genres
(
    music_id integer NOT NULL,
    genre_id integer NOT NULL,
    CONSTRAINT music_genres_pkey PRIMARY KEY (music_id, genre_id)
);

CREATE TABLE IF NOT EXISTS music.music_organization_owners
(
    music_id integer NOT NULL,
    organization_owner_id integer NOT NULL,
    date_buy date,
    date_sell date,
    CONSTRAINT music_organization_owners_pkey PRIMARY KEY (music_id, organization_owner_id)
);

CREATE TABLE IF NOT EXISTS music.organization_owners
(
    organization_owner_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    country_id integer,
    CONSTRAINT organization_owners_pkey PRIMARY KEY (organization_owner_id)
);

CREATE TABLE IF NOT EXISTS music.private_owners
(
    private_owner_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    surname text COLLATE pg_catalog."default" NOT NULL,
    second_name text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    country_id integer,
    CONSTRAINT private_owners_pkey PRIMARY KEY (private_owner_id)
);

CREATE TABLE IF NOT EXISTS music.private_owners_music
(
    private_owner_id integer NOT NULL,
    music_id integer NOT NULL,
    date_buy date,
    date_sell date,
    CONSTRAINT private_owners_music_pkey PRIMARY KEY (private_owner_id, music_id)
);

ALTER TABLE IF EXISTS music.composer
    ADD CONSTRAINT composer_country_id_fkey FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.composer
    ADD CONSTRAINT composer_country_id_fkey1 FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music
    ADD CONSTRAINT music_composer_id_fkey FOREIGN KEY (composer_id)
    REFERENCES music.composer (composer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music
    ADD CONSTRAINT music_composer_id_fkey1 FOREIGN KEY (composer_id)
    REFERENCES music.composer (composer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music
    ADD CONSTRAINT music_country_id_fkey FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music
    ADD CONSTRAINT music_country_id_fkey1 FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_genres
    ADD CONSTRAINT music_genres_genre_id_fkey FOREIGN KEY (genre_id)
    REFERENCES music.genres (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_genres
    ADD CONSTRAINT music_genres_genre_id_fkey1 FOREIGN KEY (genre_id)
    REFERENCES music.genres (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_genres
    ADD CONSTRAINT music_genres_music_id_fkey FOREIGN KEY (music_id)
    REFERENCES music.music (music_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_genres
    ADD CONSTRAINT music_genres_music_id_fkey1 FOREIGN KEY (music_id)
    REFERENCES music.music (music_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_organization_owners
    ADD CONSTRAINT music_organization_owners_music_id_fkey FOREIGN KEY (music_id)
    REFERENCES music.music (music_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_organization_owners
    ADD CONSTRAINT music_organization_owners_music_id_fkey1 FOREIGN KEY (music_id)
    REFERENCES music.music (music_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_organization_owners
    ADD CONSTRAINT music_organization_owners_organization_owner_id_fkey FOREIGN KEY (organization_owner_id)
    REFERENCES music.organization_owners (organization_owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.music_organization_owners
    ADD CONSTRAINT music_organization_owners_organization_owner_id_fkey1 FOREIGN KEY (organization_owner_id)
    REFERENCES music.organization_owners (organization_owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.organization_owners
    ADD CONSTRAINT organization_owners_country_id_fkey FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.organization_owners
    ADD CONSTRAINT organization_owners_country_id_fkey1 FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.private_owners
    ADD CONSTRAINT private_owners_country_id_fkey FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.private_owners
    ADD CONSTRAINT private_owners_country_id_fkey1 FOREIGN KEY (country_id)
    REFERENCES music.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.private_owners_music
    ADD CONSTRAINT private_owners_music_music_id_fkey FOREIGN KEY (music_id)
    REFERENCES music.music (music_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.private_owners_music
    ADD CONSTRAINT private_owners_music_music_id_fkey1 FOREIGN KEY (music_id)
    REFERENCES music.music (music_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.private_owners_music
    ADD CONSTRAINT private_owners_music_private_owner_id_fkey FOREIGN KEY (private_owner_id)
    REFERENCES music.private_owners (private_owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS music.private_owners_music
    ADD CONSTRAINT private_owners_music_private_owner_id_fkey1 FOREIGN KEY (private_owner_id)
    REFERENCES music.private_owners (private_owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;