-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS music.composer
(
    composer_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    surname text COLLATE pg_catalog."default" NOT NULL,
    second_name text COLLATE pg_catalog."default",
    country_id integer,
    date_birth date,
    date_death date,
    CONSTRAINT composer_pkey PRIMARY KEY (composer_id)
);

CREATE TABLE IF NOT EXISTS music.countries
(
    country_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT countries_pkey PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS music.genres
(
    genre_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT genres_pkey PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS music.music
(
    music_id integer NOT NULL,
    composer_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    duration text COLLATE pg_catalog."default",
    finished_date date,
    premier_date date,
    premier_place text COLLATE pg_catalog."default",
    country_id integer,
    CONSTRAINT music_pkey PRIMARY KEY (music_id)
);

CREATE TABLE IF NOT EXISTS music.music_genres
(
    music_id integer NOT NULL,
    genre_id integer NOT NULL,
    CONSTRAINT music_genres_pkey PRIMARY KEY (music_id, genre_id)
);

CREATE TABLE IF NOT EXISTS music.music_organization_owners
(
    music_id integer NOT NULL,
    organization_owner_id integer NOT NULL,
    date_buy date,
    date_sell date,
    CONSTRAINT music_organization_owners_pkey PRIMARY KEY (music_id, organization_owner_id)
);

CREATE TABLE IF NOT EXISTS music.organization_owners
(
    organization_owner_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    country_id integer,
    CONSTRAINT organization_owners_pkey PRIMARY KEY (organization_owner_id)
);

CREATE TABLE IF NOT EXISTS music.private_owners
(
    private_owner_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    surname text COLLATE pg_catalog."default" NOT NULL,
    second_name text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    country_id integer,
    CONSTRAINT private_owners_pkey PRIMARY KEY (private_owner_id)
);

CREATE TABLE IF NOT EXISTS music.private_owners_music
(
    private_owner_id integer NOT NULL,
    music_id integer NOT NULL,
    date_buy date,
    date_sell date,
    CONSTRAINT private_owners_music_pkey PRIMARY KEY (private_owner_id, music_id)
);
END;